services:
  watchtower:
      image: ghcr.io/nicholas-fedor/watchtower
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      environment:
        WATCHTOWER_POLL_INTERVAL: 300
        WATCHTOWER_LABEL_ENABLE: "true"