services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5

  api:
    image: ghcr.io/maknaeq/goonizz:dev
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:

volumes:
  pgdata: